In [1]:
#merge data from several states
import numpy as np
import pandas as pd
import json
from pandas.io.json import json_normalize
import matplotlib.pyplot as plt
import pprint
import seaborn as sns
from pprint import pprint

In [2]:
trainval = pd.read_csv('./data/trainval_set_scoped.csv')
trainval.head()

,age,gender,size,breeds.mixed,breeds.unknown,attributes.spayed_neutered,attributes.house_trained,attributes.special_needs,attributes.shots_current,contact.address.state,adoption_time
0,Young,Male,Large,True,False,True,False,False,True,MN,28
1,Baby,Female,Medium,True,False,True,False,False,True,MN,25
2,Adult,Male,Medium,True,False,True,False,False,True,CA,217
3,Young,Female,Medium,True,False,True,True,False,True,CA,1932
4,Senior,Male,Small,True,False,True,True,False,True,CA,91

In [3]:
X_features = ['age', 'gender', 'size',
       'breeds.mixed', 'breeds.unknown',
       'attributes.spayed_neutered', 'attributes.house_trained',
       'attributes.special_needs', 'attributes.shots_current', 'contact.address.state']
X = trainval[X_features]
X.head()

,age,gender,size,breeds.mixed,breeds.unknown,attributes.spayed_neutered,attributes.house_trained,attributes.special_needs,attributes.shots_current,contact.address.state
0,Young,Male,Large,True,False,True,False,False,True,MN
1,Baby,Female,Medium,True,False,True,False,False,True,MN
2,Adult,Male,Medium,True,False,True,False,False,True,CA
3,Young,Female,Medium,True,False,True,True,False,True,CA
4,Senior,Male,Small,True,False,True,True,False,True,CA

In [5]:
y = trainval['adoption_time']
y.head()

0      28
1      25
2     217
3    1932
4      91
Name: adoption_time, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
train_X, val_X, train_y, val_y = train_test_split(X, y,random_state = 0)
print('Training set size = {} and Validation set size = {}'.format(len(train_X),len(val_X)))

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
pipeline_1 = Pipeline(steps=[('model', RandomForestRegressor(random_state=0))])
pipeline_2 = Pipeline(steps=[('model', DecisionTreeRegressor(random_state=0))])
pipeline_3 = Pipeline(steps=[('model', XGBRegressor(random_state=0))])

In [ ]:
def train_RF(n_est, depth):
    rf = RandomForestRegressor(n_estimators=n_est, max_depth=depth, n_jobs=-1, random_state=0)
    pipeline_temp = Pipeline(steps=[('model', rf)])
    scores= -1 * cross_val_score(pipeline_temp, train_X, train_y,cv=5,scoring='neg_mean_absolute_error')
    print('Est: {} / Depth: {} ---- MAE: {}'.format(n_est,depth,round(scores.mean(), 3)))